# Generated by Django 4.0.4 on 2022-05-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_date_created_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_time_resolved',
        ),
    ]
