# Generated by Django 4.0.4 on 2022-05-06 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_description_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_time_created',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
